{{- if .Values.flaggerOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.flaggerOperator.serviceAccount.name | default (printf "%s-flagger-operator" (include "flagger-metrics-operator.fullname" .)) }}-cluster-role-binding
  labels:
  {{- include "flagger-metrics-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Values.flaggerOperator.serviceAccount.name | default (printf "%s-flagger-operator" (include "flagger-metrics-operator.fullname" .)) }}-cluster-role'
subjects:
- kind: ServiceAccount
  name: {{ .Values.flaggerOperator.serviceAccount.name | default (printf "%s-flagger-operator" (include "flagger-metrics-operator.fullname" .)) }}
  namespace: {{ .Values.flaggerOperator.namespace | default .Release.Namespace }}
{{- end }}
