{{- if .Values.flaggerOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.flaggerOperator.serviceAccount.name | default (printf "%s-flagger-operator" (include "flagger-metrics-operator.fullname" .)) }}
  namespace: {{ .Values.flaggerOperator.namespace | default .Release.Namespace }}
  labels:
  {{- include "flagger-metrics-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    {{- with .Values.flaggerOperator.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}