{{- if and .Values.flaggerOperator.enabled .Values.flaggerOperator.CRD.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templates.flagger.3rd.io
  labels:
  {{- include "flagger-metrics-operator.labels" . | nindent 4 }}
  annotations: 
    helm.sh/hook: pre-install
spec:
  conversion:
    strategy: None
  group: flagger.3rd.io
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Template is the Schema for the templates API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TemplateSpec defines the desired state of Template
            properties:
              namespaces:
                items:
                  properties:
                    metricTemplates:
                      items:
                        properties:
                          interval:
                            type: string
                          name:
                            type: string
                          thresholdRange:
                            properties:
                              max:
                                type: number
                            type: object
                        type: object
                      type: array
                    name:
                      type: string
                  type: object
                type: array
            type: object
          status:
            description: TemplateStatus defines the observed state of Template
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
{{- end }}