---
# Source: flagger-metrics-operator/templates/cluster-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: account-cluster-role
  labels:
    helm.sh/chart: flagger-metrics-operator-0.1.0
    app.kubernetes.io/name: flagger-metrics-operator
    app.kubernetes.io/instance: flagger-operator
    app.kubernetes.io/version: "1.2.8"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flagger.app
  resources:
  - canaries
  - metrictemplates
  verbs:
  - '*'
- apiGroups:
  - flagger.3rd.io
  resources:
  - templates
  verbs:
  - '*'
---
# Source: flagger-metrics-operator/templates/cluster-role-binding-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: account-cluster-role-binding
  labels:
    helm.sh/chart: flagger-metrics-operator-0.1.0
    app.kubernetes.io/name: flagger-metrics-operator
    app.kubernetes.io/instance: flagger-operator
    app.kubernetes.io/version: "1.2.8"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'account-cluster-role'
subjects:
- kind: ServiceAccount
  name: account
  namespace: flagger-metric-operator
---
# Source: flagger-metrics-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger-operator-flagger-metrics-operator-template
  namespace: flagger-metric-operator
  labels:
    helm.sh/chart: flagger-metrics-operator-0.1.0
    app.kubernetes.io/name: flagger-metrics-operator
    app.kubernetes.io/instance: flagger-operator
    app.kubernetes.io/version: "1.2.8"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagger-operator-template
      app.kubernetes.io/name: flagger-metrics-operator
      app.kubernetes.io/instance: flagger-operator
  template:
    metadata:
      labels:
        app: flagger-operator-template
        app.kubernetes.io/name: flagger-metrics-operator
        app.kubernetes.io/instance: flagger-operator
    spec:
      containers:
      - name: flagger-operator-template
        image: steemax/flagger-operator:v1.2.8
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
      serviceAccountName: account
---
# Source: flagger-metrics-operator/templates/basic.yaml
apiVersion: flagger.3rd.io/v1
kind: Template
metadata:
  name: basic
  namespace: flagger-metric-operator
  labels:
    app.kubernetes.io/created-by: flagger-metrics-operator
    app.kubernetes.io/part-of: flagger-metrics-operator
    helm.sh/chart: flagger-metrics-operator-0.1.0
    app.kubernetes.io/name: flagger-metrics-operator
    app.kubernetes.io/instance: flagger-operator
    app.kubernetes.io/version: "1.2.8"
    app.kubernetes.io/managed-by: Helm
spec:
  namespaces:
  - metricTemplates:
    - interval: 2m
      name: nginx-template-testing
      thresholdRange:
        max: 5
    - interval: 1m
      name: metric-template-next
      thresholdRange:
        max: 15
    name: default
---
# Source: flagger-metrics-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account
  namespace: flagger-metric-operator
  labels:
    helm.sh/chart: flagger-metrics-operator-0.1.0
    app.kubernetes.io/name: flagger-metrics-operator
    app.kubernetes.io/instance: flagger-operator
    app.kubernetes.io/version: "1.2.8"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install
---
# Source: flagger-metrics-operator/templates/template-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templates.flagger.3rd.io
  labels:
    helm.sh/chart: flagger-metrics-operator-0.1.0
    app.kubernetes.io/name: flagger-metrics-operator
    app.kubernetes.io/instance: flagger-operator
    app.kubernetes.io/version: "1.2.8"
    app.kubernetes.io/managed-by: Helm
  annotations: 
    helm.sh/hook: pre-install
spec:
  conversion:
    strategy: None
  group: flagger.3rd.io
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Template is the Schema for the templates API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TemplateSpec defines the desired state of Template
            properties:
              namespaces:
                items:
                  properties:
                    metricTemplates:
                      items:
                        properties:
                          interval:
                            type: string
                          name:
                            type: string
                          thresholdRange:
                            properties:
                              max:
                                type: number
                            type: object
                        type: object
                      type: array
                    name:
                      type: string
                  type: object
                type: array
            type: object
          status:
            description: TemplateStatus defines the observed state of Template
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
